# Generated by Django 3.0.3 on 2020-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('contact_no', models.PositiveIntegerField()),
                ('file', models.FileField(null=True, upload_to='exam_pdfs')),
            ],
        ),
    ]
