# Generated by Django 3.0.3 on 2020-04-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200408_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
