# Generated by Django 3.0.3 on 2020-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20200408_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
