# Generated by Django 3.0.3 on 2020-04-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_exam_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='comment',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='contact_no',
            new_name='semester',
        ),
    ]
