# Generated by Django 3.0.3 on 2020-04-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20200409_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='branch',
            field=models.CharField(choices=[('CS', 'CS'), ('ME', 'ME'), ('PIE', 'PIE'), ('EE', 'EE'), ('CE', 'CE'), ('ECE', 'ECE')], max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
    ]
