# Generated by Django 3.0.3 on 2020-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20200409_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
