# Generated by Django 3.0.3 on 2020-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_exam_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.AddField(
            model_name='exam',
            name='sessional',
            field=models.CharField(choices=[('MidSem 1', 'MidSem 1'), ('MidSem 2', 'MidSem 2'), ('EndSem', 'EndSem')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016')], max_length=200, null=True),
        ),
    ]
