# Generated by Django 3.0.3 on 2020-05-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20200411_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='college',
            field=models.CharField(choices=[('NIT KURUKSHETRA', 'NIT KURUKSHETRA'), ('NIT ALLAHABAD', 'NIT ALLAHABAD'), ('NIT PATNA', 'NIT PATNA'), ('NIT JAMSHEDPUR', 'NIT JAMSHEDPUR')], default='NIT KURUKSHETRA', max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('NOTES', 'NOTES'), ('PAPER', 'PAPER')], default='PAPER', max_length=200),
        ),
    ]
