# Generated by Django 3.0.3 on 2020-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_auto_20200504_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='college',
            field=models.CharField(choices=[('NIT KURUKSHETRA', 'NIT KURUKSHETRA'), ('NITALLAHABAD', 'NIT ALLAHABAD'), ('NITPATNA', 'NIT PATNA'), ('NITJAMSHEDPUR', 'NIT JAMSHEDPUR')], default='NIT KURUKSHETRA', max_length=200),
        ),
    ]
