# Generated by Django 3.0.3 on 2020-05-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_auto_20200504_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='college',
            field=models.CharField(choices=[('NIT ALLAHABAD', 'NIT ALLAHABAD'), ('NIT BHOPAL', 'NIT BHOPAL'), ('NIT CALICUT', 'NIT CALICUT'), ('NIT HAMIRPUR', 'NIT HAMIRPUR'), ('NIT JAIPUR', 'NIT JAIPUR'), ('NIT JALANDHAR', 'NIT JALANDHAR'), ('NIT JAMSHEDPUR', 'NIT JAMSHEDPUR'), ('NIT KURUKSHETRA', 'NIT KURUKSHETRA'), ('NIT NAGPUR', 'NIT NAGPUR'), ('NIT ROURKELA', 'NIT ROURKELA'), ('NIT SILCHAR', 'NIT SILCHAR'), ('NIT KARNATKA', 'NIT KARNATKA'), ('NIT WARANGAL', 'NIT WARANGAL'), ('NIT DURGAPUR', 'NIT DURGAPUR'), ('NIT SRINAGAR', 'NIT SRINAGAR'), ('NIT SURAT', 'NIT SURAT'), ('NIT TRICHY', 'NIT TRICHY'), ('NIT PATNA', 'NIT PATNA'), ('NIT RAIPUR', 'NIT RAIPUR'), ('NIT AGARTALA', 'NIT AGARTALA'), ('NIT ARUNACHALPRADESH', 'NIT ARUNACHALPRADESH'), ('NIT DELHI', 'NIT DELHI'), ('NIT GOA', 'NIT GOA'), ('NIT MANIPUR', 'NIT MANIPUR'), ('NIT MEGHALAYA', 'NIT MEGHALAYA'), ('NIT MIZORAM', 'NIT MIZORAM'), ('NIT NAGALAND', 'NIT NAGALAND'), ('NIT PUDUCHERRY', 'NIT PUDUCHERRY'), ('NIT SIKKIM', 'NIT SIKKIM'), ('NIT UTTARAKHAND', 'NIT UTTARAKHAND'), ('NIT ANDHRAPRADESH', 'NIT ANDHRAPRADESH')], default='NIT KURUKSHETRA', max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('NOTES', 'NOTES'), ('PAPER', 'PAPER')], default='NOTES', max_length=200),
        ),
    ]
