# Generated by Django 3.0.3 on 2020-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_auto_20200505_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], default=4),
        ),
    ]
