# Generated by Django 3.0.3 on 2020-05-08 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0015_auto_20200505_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDownVotes', models.ManyToManyField(blank=True, related_name='threadDownVotes', to=settings.AUTH_USER_MODEL)),
                ('userUpVotes', models.ManyToManyField(blank=True, related_name='threadUpVotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
