# Generated by Django 3.0.3 on 2020-05-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_auto_20200508_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
