# Generated by Django 3.0.3 on 2020-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_auto_20200510_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='professor',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
