# Generated by Django 3.0.3 on 2020-05-16 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_app', '0021_exam_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='college',
            field=models.CharField(choices=[('NIT-ALLAHABAD', 'NIT-ALLAHABAD'), ('NIT-BHOPAL', 'NIT-BHOPAL'), ('NIT-CALICUT', 'NIT-CALICUT'), ('NIT-HAMIRPUR', 'NIT-HAMIRPUR'), ('NIT-JAIPUR', 'NIT-JAIPUR'), ('NIT-JALANDHAR', 'NIT-JALANDHAR'), ('NIT-JAMSHEDPUR', 'NIT-JAMSHEDPUR'), ('NIT-KURUKSHETRA', 'NIT-KURUKSHETRA'), ('NIT-NAGPUR', 'NIT-NAGPUR'), ('NIT-ROURKELA', 'NIT-ROURKELA'), ('NIT-SILCHAR', 'NIT-SILCHAR'), ('NIT-KARNATKA', 'NIT-KARNATKA'), ('NIT-WARANGAL', 'NIT-WARANGAL'), ('NIT-DURGAPUR', 'NIT-DURGAPUR'), ('NIT-SRINAGAR', 'NIT-SRINAGAR'), ('NIT-SURAT', 'NIT-SURAT'), ('NIT-TRICHY', 'NIT-TRICHY'), ('NIT-PATNA', 'NIT-PATNA'), ('NIT-RAIPUR', 'NIT-RAIPUR'), ('NIT-AGARTALA', 'NIT-AGARTALA'), ('NIT-ARUNACHALPRADESH', 'NIT-ARUNACHALPRADESH'), ('NIT-DELHI', 'NIT-DELHI'), ('NIT-GOA', 'NIT-GOA'), ('NIT-MANIPUR', 'NIT-MANIPUR'), ('NIT-MEGHALAYA', 'NIT-MEGHALAYA'), ('NIT-MIZORAM', 'NIT-MIZORAM'), ('NIT-NAGALAND', 'NIT-NAGALAND'), ('NIT-PUDUCHERRY', 'NIT-PUDUCHERRY'), ('NIT-SIKKIM', 'NIT-SIKKIM'), ('NIT-UTTARAKHAND', 'NIT-UTTARAKHAND'), ('NIT-ANDHRAPRADESH', 'NIT-ANDHRAPRADESH')], default='NIT-KURUKSHETRA', max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='college',
            field=models.CharField(choices=[('NIT-ALLAHABAD', 'NIT-ALLAHABAD'), ('NIT-BHOPAL', 'NIT-BHOPAL'), ('NIT-CALICUT', 'NIT-CALICUT'), ('NIT-HAMIRPUR', 'NIT-HAMIRPUR'), ('NIT-JAIPUR', 'NIT-JAIPUR'), ('NIT-JALANDHAR', 'NIT-JALANDHAR'), ('NIT-JAMSHEDPUR', 'NIT-JAMSHEDPUR'), ('NIT-KURUKSHETRA', 'NIT-KURUKSHETRA'), ('NIT-NAGPUR', 'NIT-NAGPUR'), ('NIT-ROURKELA', 'NIT-ROURKELA'), ('NIT-SILCHAR', 'NIT-SILCHAR'), ('NIT-KARNATKA', 'NIT-KARNATKA'), ('NIT-WARANGAL', 'NIT-WARANGAL'), ('NIT-DURGAPUR', 'NIT-DURGAPUR'), ('NIT-SRINAGAR', 'NIT-SRINAGAR'), ('NIT-SURAT', 'NIT-SURAT'), ('NIT-TRICHY', 'NIT-TRICHY'), ('NIT-PATNA', 'NIT-PATNA'), ('NIT-RAIPUR', 'NIT-RAIPUR'), ('NIT-AGARTALA', 'NIT-AGARTALA'), ('NIT-ARUNACHALPRADESH', 'NIT-ARUNACHALPRADESH'), ('NIT-DELHI', 'NIT-DELHI'), ('NIT-GOA', 'NIT-GOA'), ('NIT-MANIPUR', 'NIT-MANIPUR'), ('NIT-MEGHALAYA', 'NIT-MEGHALAYA'), ('NIT-MIZORAM', 'NIT-MIZORAM'), ('NIT-NAGALAND', 'NIT-NAGALAND'), ('NIT-PUDUCHERRY', 'NIT-PUDUCHERRY'), ('NIT-SIKKIM', 'NIT-SIKKIM'), ('NIT-UTTARAKHAND', 'NIT-UTTARAKHAND'), ('NIT-ANDHRAPRADESH', 'NIT-ANDHRAPRADESH')], default='NIT-KURUKSHETRA', max_length=200),
        ),
    ]
