# Generated by Django 3.0.3 on 2020-05-17 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_auto_20200516_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
