# Generated by Django 3.0.3 on 2020-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0024_auto_20200517_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='exam',
            name='sessional',
            field=models.CharField(choices=[('MidSem 1', 'MidSem 1'), ('MidSem 2', 'MidSem 2'), ('EndSem', 'EndSem'), ('All', 'All')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='All', max_length=60),
        ),
    ]
