# Generated by Django 3.0.3 on 2020-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0025_auto_20200519_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='professor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='All', max_length=200),
        ),
    ]
