# Generated by Django 3.0.3 on 2020-06-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_auto_20200519_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.CharField(choices=[('2019-20', '2019-20'), ('2018-19', '2018-19'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016')], max_length=200, null=True),
        ),
    ]
