# Generated by Django 3.0.3 on 2020-06-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0027_auto_20200605_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.CharField(choices=[('2019-20', '2019-20'), ('2018-19', '2018-19'), ('2017-18', '2017-18')], max_length=200, null=True),
        ),
    ]
